import java.security.MessageDigest
import java.util.Properties

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
}

// Deterministic verification of complete custom OpenCV + WeChatQRCode SDK artifacts:
// 1. Completion marker generated by build_opencv_contrib_sdk.sh
val markerFile = file("src/main/.opencv-sdk-complete")
// 2. Both required 64-bit native ABIs with valid non-zero size
val arm64So = file("src/main/jniLibs/arm64-v8a/libopencv_java4.so")
val x86_64So = file("src/main/jniLibs/x86_64/libopencv_java4.so")
// 3. Essential Java bindings
val matJava = file("src/main/java/org/opencv/core/Mat.java")
val wechatJava = file("src/main/java/org/opencv/wechat_qrcode/WeChatQRCode.java")
val videoioJava = file("src/main/java/org/opencv/videoio/Videoio.java")

val expectedOpenCvVersion = "4.14.0"
val expectedOpenCvSha = "0654a42e19215ef25b1d367d822f3c630447e7c7"
val expectedContribSha = "a8e9acd62cabd30419dba83007f2ac0d07de5e2c"
val expectedAbis = "arm64-v8a,x86_64"
val expectedStatus = "VERIFIED_COMPLETE"

fun calculateSha256(file: File): String {
    val md = MessageDigest.getInstance("SHA-256")
    file.inputStream().use { stream ->
        val buffer = ByteArray(8192)
        var read: Int
        while (stream.read(buffer).also { read = it } > 0) {
            md.update(buffer, 0, read)
        }
    }
    return md.digest().joinToString("") { b -> "%02x".format(b) }
}

fun validateMarkerMetadata(file: File): Boolean {
    if (!file.exists() || file.length() == 0L) return false
    val props = Properties()
    return try {
        file.inputStream().use { props.load(it) }
        val baseValid = props.getProperty("OpenCV") == expectedOpenCvVersion &&
            props.getProperty("OpenCV_SHA") == expectedOpenCvSha &&
            props.getProperty("Contrib_SHA") == expectedContribSha &&
            props.getProperty("ABIs") == expectedAbis &&
            props.getProperty("Status") == expectedStatus

        if (!baseValid) return false

        val expectedArm64Sha = props.getProperty("ARM64_SHA256") ?: return false
        val expectedX86Sha = props.getProperty("X86_64_SHA256") ?: return false

        if (!arm64So.exists() || calculateSha256(arm64So) != expectedArm64Sha) {
            return false
        }
        if (!x86_64So.exists() || calculateSha256(x86_64So) != expectedX86Sha) {
            return false
        }

        true
    } catch (_: Exception) {
        false
    }
}

val isMarkerValid = validateMarkerMetadata(markerFile)
val isCustomSdkComplete = isMarkerValid &&
    arm64So.exists() && arm64So.length() > 0L &&
    x86_64So.exists() && x86_64So.length() > 0L &&
    matJava.exists() && wechatJava.exists() && videoioJava.exists()

android {
    // Namespace is org.opencv so AGP generates org.opencv.R and org.opencv.BuildConfig
    // expected by CameraBridgeViewBase, CameraGLSurfaceView, and custom CV native components.
    namespace = "org.opencv"
    compileSdk = 35

    buildFeatures {
        buildConfig = true
    }

    lint {
        abortOnError = false
        checkReleaseBuilds = false
    }

    defaultConfig {
        minSdk = 26
        consumerProguardFiles("consumer-rules.pro")
        ndk {
            abiFilters.addAll(listOf("arm64-v8a", "x86_64"))
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs = freeCompilerArgs + listOf(
            "-opt-in=kotlin.ExperimentalUnsignedTypes",
            "-opt-in=kotlin.RequiresOptIn",
        )
    }

    packaging {
        jniLibs {
            keepDebugSymbols += listOf("**/*.so")
        }
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
    }
}

dependencies {
    if (isCustomSdkComplete) {
        logger.lifecycle(":opencv-sdk compiling with complete in-tree custom OpenCV SDK (OpenCV=$expectedOpenCvVersion, SHA=${expectedOpenCvSha.take(8)})")
    }
}

// Fail closed if custom SDK artifacts are missing or invalid when building :opencv-sdk or packaging :app
gradle.taskGraph.whenReady {
    val finalArtifactTaskNames = setOf(
        "assemble", "assembleDebug", "assembleRelease",
        "packageDebug", "packageRelease",
        "bundle", "bundleDebug", "bundleRelease",
        "bundleDebugAar", "bundleReleaseAar"
    )
    val requiresCustomSdk = allTasks.any { task ->
        (task.project == project || task.project.name == "app") &&
            task.name in finalArtifactTaskNames
    }
    if (requiresCustomSdk && !isCustomSdkComplete) {
        throw GradleException(
            "FATAL: Custom OpenCV SDK is missing or incomplete in :opencv-sdk! " +
            "A verified in-tree custom OpenCV build (with WeChatQRCode, native ABIs, and .opencv-sdk-complete marker) " +
            "is strictly mandatory. Build OpenCV using android/scripts/build_opencv_contrib_sdk.sh before building :opencv-sdk or packaging :app."
        )
    }
}
