import java.util.Properties

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.veilframe.opencv"
    compileSdk = 35

    defaultConfig {
        minSdk = 26
        consumerProguardFiles("consumer-rules.pro")
        ndk {
            abiFilters.addAll(listOf("arm64-v8a", "x86_64"))
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
    }
}

// Deterministic verification of complete custom OpenCV + WeChatQRCode SDK artifacts:
// 1. Completion marker generated by build_opencv_contrib_sdk.sh
val markerFile = file("src/main/.opencv-sdk-complete")
// 2. Both required 64-bit native ABIs with valid non-zero size
val arm64So = file("src/main/jniLibs/arm64-v8a/libopencv_java4.so")
val x86_64So = file("src/main/jniLibs/x86_64/libopencv_java4.so")
// 3. Essential Java bindings
val matJava = file("src/main/java/org/opencv/core/Mat.java")
val wechatJava = file("src/main/java/org/opencv/wechat_qrcode/WeChatQRCode.java")

val expectedOpenCvVersion = "4.14.0"
val expectedOpenCvSha = "0654a42b10ba2dc2b0d00f73fbfb534442654ee0"
val expectedContribSha = "a8e9acdd94489bb2df921e64906a5efdcfdae267"
val expectedAbis = "arm64-v8a,x86_64"
val expectedStatus = "VERIFIED_COMPLETE"

fun validateMarkerMetadata(file: File): Boolean {
    if (!file.exists() || file.length() == 0L) return false
    val props = Properties()
    return try {
        file.inputStream().use { props.load(it) }
        props.getProperty("OpenCV") == expectedOpenCvVersion &&
            props.getProperty("OpenCV_SHA") == expectedOpenCvSha &&
            props.getProperty("Contrib_SHA") == expectedContribSha &&
            props.getProperty("ABIs") == expectedAbis &&
            props.getProperty("Status") == expectedStatus
    } catch (_: Exception) {
        false
    }
}

val isMarkerValid = validateMarkerMetadata(markerFile)
val isCustomSdkComplete = isMarkerValid &&
    arm64So.exists() && arm64So.length() > 0L &&
    x86_64So.exists() && x86_64So.length() > 0L &&
    matJava.exists() && wechatJava.exists()

dependencies {
    if (isCustomSdkComplete) {
        logger.lifecycle(":opencv-sdk compiling with complete in-tree custom OpenCV SDK (OpenCV=$expectedOpenCvVersion, SHA=${expectedOpenCvSha.take(8)})")
    } else {
        // Detect partial/broken/forged artifacts to alert developer
        val hasPartialSo = file("src/main/jniLibs").exists() &&
            file("src/main/jniLibs").walkTopDown().any { it.extension == "so" }
        val hasPartialJava = file("src/main/java").exists() &&
            file("src/main/java").walkTopDown().any { it.extension == "java" }
        if (markerFile.exists() && !isMarkerValid) {
            logger.warn(":opencv-sdk WARNING: Completion marker failed deterministic build metadata validation (expected OpenCV=$expectedOpenCvVersion SHA=${expectedOpenCvSha.take(8)}, Contrib SHA=${expectedContribSha.take(8)}, ABIs=$expectedAbis)! Safely falling back to verified Maven distribution.")
        } else if (hasPartialSo || hasPartialJava || markerFile.exists()) {
            logger.warn(":opencv-sdk WARNING: Incomplete custom OpenCV artifacts detected (missing required ABIs, Java bindings, or valid marker)! Safely falling back to verified Maven distribution.")
        } else {
            logger.lifecycle(":opencv-sdk using vetted Maven WeChatQRCode OpenCV distribution (transitional baseline)")
        }
        api("com.github.jenly1314.WeChatQRCode:opencv:2.6.0")
        api("com.github.jenly1314.WeChatQRCode:opencv-armv64:2.6.0")
        api("com.github.jenly1314.WeChatQRCode:opencv-x86_64:2.6.0")
    }
}
