"""
veilframe.folder.ai_bundle.formats.markdown — GitHub-flavored Markdown bundle renderer.
"""

from __future__ import annotations

from typing import List, Tuple

from veilframe.folder.ai_bundle.bundle_config import BundleConfig
from veilframe.folder.ai_bundle.manifest_renderer import render_manifest_summaries
from veilframe.folder.ai_bundle.project_summary import generate_project_metadata, render_project_summary_text
from veilframe.folder.ai_bundle.relationship_renderer import render_project_relationships
from veilframe.folder.ai_bundle.tree_renderer import build_project_tree
from veilframe.folder.models.classification import FileCategory
from veilframe.folder.models.file_record import FileRecord
from veilframe.folder.models.scan_result import ScanResult


def _lang_to_fence(lang: str) -> str:
    """Map language name to markdown syntax highlighter identifier."""
    if not lang:
        return ""
    l = lang.lower()
    mapping = {
        "python": "python",
        "javascript": "javascript",
        "typescript": "typescript",
        "rust": "rust",
        "go": "go",
        "c": "c",
        "c++": "cpp",
        "cpp": "cpp",
        "c#": "csharp",
        "csharp": "csharp",
        "java": "java",
        "kotlin": "kotlin",
        "scala": "scala",
        "php": "php",
        "ruby": "ruby",
        "swift": "swift",
        "dart": "dart",
        "shell": "bash",
        "bash": "bash",
        "powershell": "powershell",
        "yaml": "yaml",
        "json": "json",
        "markdown": "markdown",
        "sql": "sql",
        "html": "html",
        "css": "css",
    }
    return mapping.get(l, l)


def render_markdown_bundle(
    scan_result: ScanResult,
    config: BundleConfig,
    included_files: List[Tuple[FileRecord, str, int]],
    excluded_files: List[Tuple[FileRecord, str]],
    total_tokens: int,
) -> str:
    """Render project bundle as comprehensive GitHub-Flavored Markdown."""
    meta = generate_project_metadata(scan_result)
    parts: List[str] = [
        f"# {meta['name']} — AI Project Bundle",
        f"\n*Generated by VeilFrame 2.x • Estimated Context: {total_tokens:,} tokens*\n",
    ]

    # Security Warnings Callout
    if scan_result.security_alerts:
        parts.append("## ⚠️ Security Alerts\n")
        parts.append("> [!WARNING]")
        parts.append("> Potential secrets or sensitive credentials detected:")
        for alert in scan_result.security_alerts:
            parts.append(f"> - `{alert.relative_path}` ({alert.rule_id}): {alert.description}")
        parts.append("")

    # Project Overview Table
    parts.append("## Project Overview\n")
    parts.append("| Metric | Value |")
    parts.append("| :--- | :--- |")
    parts.append(f"| **Root Path** | `{meta['root']}` |")
    parts.append(f"| **Languages** | {', '.join(meta['languages']) if meta['languages'] else 'None'} |")
    parts.append(f"| **Ecosystems** | {', '.join(meta['ecosystems']) if meta['ecosystems'] else 'Generic'} |")
    parts.append(f"| **Files Included** | {len(included_files):,} of {meta['total_files']:,} |")
    parts.append(f"| **Estimated Tokens** | ~{total_tokens:,} |")
    parts.append("")

    # Directory Tree
    if config.include_tree:
        files_for_tree = [f for f, _, _ in included_files]
        tree_text = build_project_tree(files_for_tree)
        parts.append("<details open><summary><b>Directory Structure</b></summary>\n")
        parts.append("```text")
        parts.append(tree_text)
        parts.append("```\n</details>\n")

    # Dependency Manifests
    if config.include_manifests:
        all_recs = [f for f, _, _ in included_files]
        man_text = render_manifest_summaries(all_recs)
        if man_text and "No standard" not in man_text:
            parts.append("## Dependency Manifests\n")
            parts.append("```yaml")
            parts.append(man_text)
            parts.append("```\n")

    # Module Relationships
    if config.include_relationships:
        all_recs = [f for f, _, _ in included_files]
        rel_text = render_project_relationships(all_recs, scan_result.project_graph)
        if rel_text and "No intra-project" not in rel_text:
            parts.append("## Architectural Relationships\n")
            parts.append("```text")
            parts.append(rel_text)
            parts.append("```\n")

    # Source Files
    parts.append("## Project Files\n")
    for f, content, tokens in included_files:
        fence = _lang_to_fence(f.language or "")
        parts.append(f"### `{f.relative_path}`")
        parts.append(f"*Category: {f.effective_category.value} | Language: {f.language or 'Text'} | Tokens: ~{tokens:,}*\n")
        parts.append(f"```{fence}")
        parts.append(content.strip())
        parts.append("```\n")

    # Excluded files section
    if config.include_excluded_list and excluded_files:
        parts.append("<details><summary><b>Excluded Files List</b></summary>\n")
        parts.append("| File | Reason |")
        parts.append("| :--- | :--- |")
        for f, reason in excluded_files[:150]:
            parts.append(f"| `{f.relative_path}` | {reason} |")
        if len(excluded_files) > 150:
            parts.append(f"| ... | *{len(excluded_files) - 150} additional files excluded* |")
        parts.append("\n</details>\n")

    return "\n".join(parts)
